### ISSUE TITLE
CASSIE UIU announcement dosen't play randomly

### ISSUE THREAD

**Issue by DinoNuggets2** [Marco15453/UIURescueSquad#11]
So randomly when UIU will spawn, the CASSIE announcement you set up for when they spawn doesn't play sometimes. It isn't that big of an issue, but it would be nice if UIU's announcement played all the time.

**Comment by Marco15453** [comment]
Is this issue still occurs at the current release?

**Comment by FinnFurwolf** [comment]
Yes
