### ISSUE TITLE
Player Nametags not appearing

### ISSUE THREAD

**Issue by DinoNuggets2** [Marco15453/UIURescueSquad#16]
Any UIU member's tag won't appear when they are playing

**Result of Show Plugins in console**
                           Enabled plugins: 35
                           Disabled plugins: 0
                           
                           CedMod:
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm
                                - Priority: Highest
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           Spectator Shooting Range:
                                - Author: rayzer
                                - Version: 2.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: spectator_shooting_range
                                - Priority: Higher
                           Infiltrated:
                                - Author: Twitch.tv/Monaldcry7788#9248
                                - Version: 5.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: infiltrated
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: SD
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           SCPLockdown:
                                - Author: Raul125
                                - Version: 2.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: scp_lockdown
                                - Priority: Medium
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Author: Michal78900
                                - Version: 4.1.0
                                - Required Exiled Version: 4.1.2
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           CedMod-WebAPI:
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_WAPI
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 5.1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           Scp035:
                                - Author: Joker119
                                - Version: 4.0.2
                                - Required Exiled Version: 4.2.0
                                - Prefix: Scp035
                                - Priority: Medium
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 4.0.2.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           CustomDoorAccess:
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK
                                - Version: 3.0.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: ST106
                                - Priority: Medium
                           BetterDrops:
                                - Author: Jesus-QC
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7
                                - Prefix: better_drops
                                - Priority: Medium
                           SummonRespawnVehicles:
                                - Author: 
                                - Version: 1.0.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: summon_respawn_vehicles
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.8.2
                                - Required Exiled Version: 4.2.2
                                - Prefix: nuke_lock
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 4.0.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: AT
                                - Priority: Medium
                           LightsRE:
                                - Author: Beryl - (Contributors: BuildBoy12)
                                - Version: 4.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: lights
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, maintained by Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           CedMod-SampleEvent:
                                - Author: ced777ric#8321
                                - Version: 0.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_sampleevent
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           MapEditorReborn:
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 2.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           CedMod-Events:
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_events
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest

I'm not sure if you need to test every plugin, but incase you do that is the list

**Comment by Remi321** [comment]
I have the same issue on my server.

**Comment by PatPeter** [comment]
Can confirm, the color tags are broken which is causing this issue:

![Corrupt team names and squad names](https://i.imgur.com/stUUD16.jpg)

**Comment by Marco15453** [comment]
Is this issue still occurs in the current release?

**Comment by FinnFurwolf** [comment]
No

**Comment by Marco15453** [comment]
Issue seems to be resolved
