### ISSUE TITLE
No UIU cassie announcement

### ISSUE THREAD

**Issue by LaFesta1749** [Marco15453/UIURescueSquad#22]
The plugin doesn't announce when a squad of UIU spawns via Cassie. It just says NTF spawn etc (as per game default)

**Comment by LaFesta1749** [comment]
I've tested around the config and it butchers the announcements since CASSIE doesn't have a lot of words to work with

**Comment by Marco15453** [comment]
Is this bug fixed?

**Comment by FinnFurwolf** [comment]
Working perfectly for me.

**Comment by Marco15453** [comment]
Bug has been fixed
