### ISSUE TITLE
UIU Spawns in the Void.

### ISSUE THREAD

**Issue by SnivyFilms** [Marco15453/UIURescueSquad#23]
When a UIU spawnwave happens, the UIU operatives spawns in the void.

Expected behavior: A spawnwave occurs on the surface. This takes place EVEN when given a custom spawnpoint.

Version: UIU V 4.0.0 Testing Release, Exiled 6.1.0 RC 1

Server Logs
[Round 2023-05-03 20.37.50.txt](https://github.com/Marco15453/UIURescueSquad/files/11391186/Round.2023-05-03.20.37.50.txt)

**Comment by Marco15453** [comment]
Please adjust the spawn position of the Roles.

**Comment by SnivyFilms** [comment]
UIU V 4.1.0 Testing Release fixes this issue. Thank you
