### ISSUE TITLE
UIU Spawns more than the config specified

### ISSUE THREAD

**Issue by SnivyFilms** [Marco15453/UIURescueSquad#24]
UIU Spawns way more often than the hard cap that the config file has specified.

Expected behavior: UIU only spawns once as the config is set as by default.

Release: UIU Rescue Squad V 4.0.0 Testing Release, Exiled 6.1.0 RC 1

Server Log (Yes it is the same one as the other bug report I made)
[Round 2023-05-03 20.37.50.txt](https://github.com/Marco15453/UIURescueSquad/files/11391204/Round.2023-05-03.20.37.50.txt)

**Comment by Marco15453** [comment]
The Config Respawns, as i think you mean is there declared to wait until that amount of MTFs spawns until there is a chance that UIU can spawn. Respawns Config Description "How many mtfs respawns must have happened to spawn UIU"

**Comment by SnivyFilms** [comment]
Yeah. You're right regarding that, I read it as the max amount of spawns that uiu can spawn in. My bad

**Comment by Marco15453** [comment]
All good, I have added an option in version 4.1.0 - Testing Release that adds a maximum that can spawn :)

**Comment by SnivyFilms** [comment]
I'll test it later today to see if the UIU Spawnwave cap works, I'll get back to you.
