### ISSUE TITLE
UIU Spawnteam command doesn't work properly

### ISSUE THREAD

**Issue by SnivyFilms** [Marco15453/UIURescueSquad#25]
Describe the Bug: When executing the command UIU Spawnteam command it spawns an MTF spawnwave, giving the equipment that the MTF Squad would have.

To Reproduce:
Have a few people in spectator, and run the command UIU spawnteam, when the spawn wave happens everyone is just MTF

Expected Behavior: 
The spawnwave spawns in as UIU

Screenshots:
N/A

UIU Version:
UIU Rescue Squad V 4.1.0 Testing Release

Server Logs:
[Round 2023-05-04 12.52.05.txt](https://github.com/Marco15453/UIURescueSquad/files/11398022/Round.2023-05-04.12.52.05.txt)

**Comment by Marco15453** [comment]
Could you make a video?

**Comment by SnivyFilms** [comment]
https://user-images.githubusercontent.com/120346554/236294540-51d86eb0-0b7a-4e1e-8fdf-36123f178166.mp4

I also updated to V 4.1.1 Testing release
More context: I have UIU spawn in a different location and have different loadouts

**Comment by Marco15453** [comment]
alright, I'll look intro it.

**Comment by Marco15453** [comment]
This Issue should been fixed with the newest update
