### ISSUE TITLE
[Bug] Plugin ignores configured spawn delay

### ISSUE THREAD

**Issue by FinnFurwolf** [Marco15453/UIURescueSquad#27]
I left the spawn delay untouched, so there has to be at least one Chaos or MTF Respawn for UIU to appear, but UIU can still spawn on first wave.

**Comment by FinnFurwolf** [comment]
I noticed this happening with Serpent's Hand, too. After setting respawn_delay to 2, it could only spawn on second wave, as originally intended, so both plugins seem to maybe count the round starting as first spawn wave or sth.

**Comment by Marco15453** [comment]
This Issue should been fixed with the newest update
