### ISSUE TITLE
[Standard Config] Outdated resource

### ISSUE THREAD

**Issue by FinnFurwolf** [Marco15453/UIURescueSquad#29]
For the UIU loadout is "GrenadeFrag" filled out in the standard configuration, but this name is outdated, so they don't get a grenade ingame. The new correct name would be "GrenadeHE".

**Comment by Marco15453** [comment]
Alright, Thanks for letting me know, I'll fix it in the next update.

**Comment by Marco15453** [comment]
Config has been adjusted
