### ISSUE TITLE
[enhancement] Adding delay for NTF and UIUSquad appearance.

### ISSUE THREAD

**Issue by iojforever** [Marco15453/UIURescueSquad#8]
### If Michal78900 isnt interested, then this issue serves no purpose.

> **NTF appearance delay:**

_My idea echoes the concept of the original plugin idea, allowing to move the squad [UIUSquad and NTF] to a different location for a certain period of time._

> **Why is this necessary?**

_A short time pause of the NTF appearance near facility, during which they can discuss a plan of action instead of running forward crazily, seems fit to the original concept. Its like a delay for NTF group before they will spawn, but also allows them to talk with each others. At least can help them prepare their weapon to avoid SpawnKill._

> **Why i ask you to add it instead of asking new plugin?**

_You've already worked on plugins like WaitAndChillReborn that contains the same room-chill feature, and the UIUResqueSquad plugin gives you the ability to modify CASSIE for NTF, which partially includes editing the built-in NTF functionality, so adding some kind of "headquarters" for NTF and UIUSquad both where they can prepare and discuss anything they like will make situation more unusual._

> **Config adaptation variation:**

UIUResqueSquad
. . .
# Should NTF group appearance be delayed?
enable_delay: bool
# For how long NTF group appearance should be delayed? (Null to disable it)
delay: int
# Which locations should contain NTF group until timer will expire?
containment_rooms:
- SHELTER
- TOWER1

**Comment by Michal78900** [comment]
The concept is good, but this is probably difficult to make.

For starters I need to completly override the enitre respawn system to execute about these 60 seconds earlier. Other than that I need to spawn players that died recently as a correct role.

As I said the concept is good and I may consider it in a future but I'm affraid this could be hard to maintain (for example plugins that depend on respawning may not work or something)
