### ISSUE TITLE
New Config Suggestion

### ISSUE THREAD

**Issue by tpd1864blake** [Marco15453/UIURescueSquad#9]
It would be cool if there was a config file to edit UIU's friendly fire rules with other NTF, so that server owners can get creative with this team's gameplay impact.

For example, a server owner could rename any reference of Unusual Incidents Unit to Global Occult Coalition and set their friendly fire rules to true with MTF, Scientists, and Facility Guards. There would be no need to edit the win conditions to make them neutral with these classes in this case.

**Comment by tpd1864blake** [comment]
Expanding on this idea, there should be more configurations to better mirror Serpent's Hand (especially from recent updates), and kind of make this an "anti-class" of TSH. For example, limiting the number of spawns that can occur before UIU will never be spawned. I think it would be easier for people to understand how to configure this plugin if it had all the same config as TSH and was made apparent that this class is supposed to counter Serpent's Hand. Here's an example config that sums up all the ideas mentioned:
# UIURescueSquad

# Configs
| Config        | Value Type | Default Value | Description |
| :-------------: | :---------: | :------: | :--------- |
| `friendly_fire` | List\<string> | - | List of classes that UIU can kill, and vice versa. Keep empty to disable Friendly Fire. Ignored if Friendly Fire is enabled in Server Settings.
| `max_spawns` | int | 2 | The maximum number of times UIU can spawn per game.
| `can_spawn_without_scps` | bool | false | Determines if UIU should be able to spawn when there is no SCPs.

**Comment by Michal78900** [comment]
These will be added after 11.0 update, because I don't know how many things will break

(Also, I'm really sorry I anwserwing a month after your comment. For some reason I didn't see this issue.)
